[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
cdbd_spl = "3iCbv94ivHb4of8NEeikMbk2kckLVSDmUEprpQZ1cBUw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/heb/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
